# Database
db.File=jdbc:sqlite:Storage\\Database\\EXOBOT.sqlite
db.User=usuario
db.Pass=secreta

# # Datafile
#df.AntCoor=Storage\\DataFiles\\pat_mic.csv
#df.AntNest=Storage\\DataFiles\\AntNest.txt
#df.AntFood=Storage\\DataFiles\\AntFood.txt

# Logs
df.logFile=Storage/Logs/AppErrors.log

# Resource
res.img.Main=   /Infrastructure/Resources/img/MainExoBot.png
res.img.Logo=   /Infrastructure/Resources/img/LogoExoBot.png
res.img.Splash= /Infrastructure/Resources/img/SplashExoBot.png
